services:

  nginx:
    container_name: "docker-nginx"
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/static:/usr/share/nginx/static"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/ssl:/etc/nginx/ssl"
    environment:
      TZ: Asia/Shanghai
    restart: always